<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Amount ($)'                            => 'Сумма $',
    'For user'                              => 'Подотчетная',
    'Time'                                  => 'Время',
    'Amount'                                => 'Сумма',
    'Article'                               => 'Статья',
    'Balance:'                              => 'Баланс:',
    'Cash Entry/Withdrawal'                 => 'Внесение/Снятие в кассу',
    'Cash operations'                       => 'Кассовае операции',
    'Comment'                               => 'Коммент',
    'Create new report'                     => 'Создать отчет',
    'Created At'                            => 'Время',
    'Entry'                                 => 'Поступление',
    'ID'                                    => 'ID',
    'In cash:'                              => 'В кассе:',
    'Incorrect login or password.'          => 'Неверный логие или пароль.',
    'Is Debit'                              => 'Поступление',
    'Is For User'                           => 'Подотчетная',
    'Login'                                 => 'Логин',
    'New report'                            => 'Новый отчет',
    'No'                                    => 'Нет',
    'Operation has been done successfully.' => 'Опереция выполнена успешно.',
    'Operations'                            => 'Операции',
    'Password'                              => 'Пароль',
    'Person Entry/Withdrawal'               => 'Внесение/Снятие подотчетных средств',
    'Report has been created successfully.' => 'Отчет создан успешно',
    'Reports'                               => 'Отчеты',
    'Type'                                  => 'Тип',
    'User'                                  => 'Пользователь',
    'User ID'                               => 'ID',
    'Withdrawal'                            => 'Списание',
    'Yes'                                   => 'Да',
    "Logout"                                => "Выйти"
];
